name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 21
          distribution: zulu

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gradle Build
        run: ./gradlew build
